"""
Centralized configuration for the Threat Intelligence module.

This module contains only immutable configuration constants shared across
all external Threat Intelligence providers.

Responsibilities
----------------
- API endpoints
- Network configuration
- Timeout configuration
- Cache policy
- Polling policy
- Rate-limit metadata

Do NOT store:
- API Keys
- Secrets
- Business Logic
"""

from __future__ import annotations

# HTTP Configuration
DEFAULT_HTTP_TIMEOUT: float = 10.0
DEFAULT_USER_AGENT: str = (
    "AI-URL-Fraud-Detection-System/2.0 (Enterprise-Gateway)"
)
MAX_REDIRECTS: int = 5
MAX_KEEPALIVE_CONNECTIONS: int = 20
MAX_CONNECTIONS: int = 100


# Retry Policy
DEFAULT_RETRY_COUNT: int = 2


# Cache Configuration
CACHE_PREFIX: str = "threat_intel"
DEFAULT_CACHE_TTL_SECONDS: int = 60 * 60 * 24  # 24 hours
VIRUSTOTAL_CACHE_TTL_SECONDS: int = DEFAULT_CACHE_TTL_SECONDS
GOOGLE_SAFE_BROWSING_CACHE_TTL_SECONDS: int = DEFAULT_CACHE_TTL_SECONDS
PHISHTANK_CACHE_TTL_SECONDS: int = DEFAULT_CACHE_TTL_SECONDS
URLSCAN_CACHE_TTL_SECONDS: int = DEFAULT_CACHE_TTL_SECONDS
IPQS_CACHE_TTL_SECONDS: int = DEFAULT_CACHE_TTL_SECONDS


# VirusTotal
VIRUSTOTAL_BASE_URL: str = "https://www.virustotal.com/api/v3"
VIRUSTOTAL_SCAN_ENDPOINT: str = "/urls"
VIRUSTOTAL_RESULT_ENDPOINT: str = "/analyses/{analysis_id}"
VIRUSTOTAL_POLL_INTERVAL_SECONDS: int = 3
VIRUSTOTAL_MAX_POLL_TIME_SECONDS: int = 30
VIRUSTOTAL_DAILY_RATE_LIMIT: int = 500


# Google Safe Browsing

GOOGLE_SAFE_BROWSING_BASE_URL: str = (
    "https://safebrowsing.googleapis.com/v4"
)

GOOGLE_SAFE_BROWSING_LOOKUP_ENDPOINT: str = (
    "/threatMatches:find"
)
GOOGLE_SAFE_BROWSING_TIMEOUT_SECONDS: int = 3


# URLHaus
URLHAUS_BASE_URL: str = "https://urlhaus-api.abuse.ch"
URLHAUS_LOOKUP_ENDPOINT: str = "/v1/url/"
URLHAUS_TIMEOUT_SECONDS: int = 5


# PhishTank

PHISHTANK_BASE_URL: str = (
    "https://checkurl.phishtank.com"
)
PHISHTANK_LOOKUP_ENDPOINT: str = "/checkurl/"
PHISHTANK_TIMEOUT_SECONDS: int = 5


# URLScan

URLSCAN_BASE_URL: str = "https://urlscan.io/api/v1"
URLSCAN_SUBMIT_ENDPOINT: str = "/scan"
URLSCAN_RESULT_ENDPOINT: str = "/result/{uuid}"
URLSCAN_TIMEOUT_SECONDS: int = 65
URLSCAN_POLL_INTERVAL_SECONDS: int = 3
URLSCAN_MAX_POLL_TIME_SECONDS: int = 60
URLSCAN_DAILY_RATE_LIMIT: int = 5000
URLSCAN_PROVIDER_NAME: str = "URLScan"
URLSCAN_MALICIOUS_LOG_THRESHOLD: int = 30  
URLSCAN_MAX_NETWORK_REQUESTS_TO_PARSE: int = 200  


# AbuseIPDB
ABUSEIPDB_BASE_URL: str = "https://api.abuseipdb.com/api/v2"
ABUSEIPDB_TIMEOUT_SECONDS: int = 5


# Logging

LOG_REQUEST_START: str = "Sending request to provider: %s"
LOG_REQUEST_SUCCESS: str = "Provider %s completed successfully."
LOG_REQUEST_FAILURE: str = "Provider %s failed."
LOG_RATE_LIMIT: str = "Provider %s exceeded rate limit."
LOG_TIMEOUT: str = "Provider %s timed out."


# Default Risk Thresholds
# (Used by Threat Intelligence Calculator)

BLACKLIST_HIT_WEIGHT: int = 30
SUSPICIOUS_PROVIDER_WEIGHT: int = 15
HIGH_CONFIDENCE_THRESHOLD: int = 80
MEDIUM_CONFIDENCE_THRESHOLD: int = 50
LOW_CONFIDENCE_THRESHOLD: int = 20

# Magic number constants migrated to Config
VIRUSTOTAL_MALICIOUS_THRESHOLD: int = 3
ABUSEIPDB_MALICIOUS_THRESHOLD: int = 80
ABUSEIPDB_SUSPICIOUS_THRESHOLD: int = 40
ABUSEIPDB_REPORTS_THRESHOLD: int = 10
URLSCAN_LOCAL_MALICIOUS_THRESHOLD: float = 0.7
URLSCAN_LOCAL_SUSPICIOUS_THRESHOLD: float = 0.4
URLSCAN_FORM_MALICIOUS_THRESHOLD: float = 0.8
URLSCAN_FORM_SUSPICIOUS_THRESHOLD: float = 0.5
URLSCAN_HOSTING_SUSPICIOUS_THRESHOLD: float = 0.7
URLSCAN_REDIRECT_THRESHOLD: int = 3
URLSCAN_GLOBAL_MALICIOUS_THRESHOLD: float = 0.8
URLSCAN_MALICIOUS_SCORE_THRESHOLD: int = 80

BLACKLIST_SCORE_WEIGHT: int = 40
BEHAVIORAL_SCORE_WEIGHT: int = 25
REPUTATION_SCORE_WEIGHT: int = 15

HIGH_RISK_THRESHOLD: int = 50
MEDIUM_RISK_THRESHOLD: int = 15



class ThreatIntelConfig:
    DEFAULT_HTTP_TIMEOUT: float = DEFAULT_HTTP_TIMEOUT
    DEFAULT_USER_AGENT: str = DEFAULT_USER_AGENT
    MAX_REDIRECTS: int = MAX_REDIRECTS
    MAX_KEEPALIVE_CONNECTIONS: int = MAX_KEEPALIVE_CONNECTIONS
    MAX_CONNECTIONS: int = MAX_CONNECTIONS

    DEFAULT_RETRY_COUNT: int = DEFAULT_RETRY_COUNT

    CACHE_PREFIX: str = CACHE_PREFIX
    DEFAULT_CACHE_TTL_SECONDS: int = DEFAULT_CACHE_TTL_SECONDS
    VIRUSTOTAL_CACHE_TTL_SECONDS: int = VIRUSTOTAL_CACHE_TTL_SECONDS
    GOOGLE_SAFE_BROWSING_CACHE_TTL_SECONDS: int = GOOGLE_SAFE_BROWSING_CACHE_TTL_SECONDS
    PHISHTANK_CACHE_TTL_SECONDS: int = PHISHTANK_CACHE_TTL_SECONDS
    URLSCAN_CACHE_TTL_SECONDS: int = URLSCAN_CACHE_TTL_SECONDS
    IPQS_CACHE_TTL_SECONDS: int = IPQS_CACHE_TTL_SECONDS

    VIRUSTOTAL_BASE_URL: str = VIRUSTOTAL_BASE_URL
    VIRUSTOTAL_SCAN_ENDPOINT: str = VIRUSTOTAL_SCAN_ENDPOINT
    VIRUSTOTAL_RESULT_ENDPOINT: str = VIRUSTOTAL_RESULT_ENDPOINT
    VIRUSTOTAL_POLL_INTERVAL_SECONDS: int = VIRUSTOTAL_POLL_INTERVAL_SECONDS
    VIRUSTOTAL_MAX_POLL_TIME_SECONDS: int = VIRUSTOTAL_MAX_POLL_TIME_SECONDS
    VIRUSTOTAL_DAILY_RATE_LIMIT: int = VIRUSTOTAL_DAILY_RATE_LIMIT

    # Custom attributes required by virustotal_provider.py
    VIRUSTOTAL_TIMEOUT: float = 35.0
    VIRUSTOTAL_POLL_INTERVAL: int = VIRUSTOTAL_POLL_INTERVAL_SECONDS
    VIRUSTOTAL_MAX_POLL_ATTEMPTS: int = VIRUSTOTAL_MAX_POLL_TIME_SECONDS // VIRUSTOTAL_POLL_INTERVAL_SECONDS

    GOOGLE_SAFE_BROWSING_BASE_URL: str = GOOGLE_SAFE_BROWSING_BASE_URL
    GOOGLE_SAFE_BROWSING_LOOKUP_ENDPOINT: str = GOOGLE_SAFE_BROWSING_LOOKUP_ENDPOINT
    GOOGLE_SAFE_BROWSING_TIMEOUT_SECONDS: int = GOOGLE_SAFE_BROWSING_TIMEOUT_SECONDS

    URLHAUS_BASE_URL: str = URLHAUS_BASE_URL
    URLHAUS_LOOKUP_ENDPOINT: str = URLHAUS_LOOKUP_ENDPOINT
    URLHAUS_TIMEOUT_SECONDS: int = URLHAUS_TIMEOUT_SECONDS

    PHISHTANK_BASE_URL: str = PHISHTANK_BASE_URL
    PHISHTANK_LOOKUP_ENDPOINT: str = PHISHTANK_LOOKUP_ENDPOINT
    PHISHTANK_TIMEOUT_SECONDS: int = PHISHTANK_TIMEOUT_SECONDS

    URLSCAN_BASE_URL: str = URLSCAN_BASE_URL
    URLSCAN_PROVIDER_NAME: str = URLSCAN_PROVIDER_NAME
    URLSCAN_SUBMIT_ENDPOINT: str = URLSCAN_SUBMIT_ENDPOINT
    URLSCAN_RESULT_ENDPOINT: str = URLSCAN_RESULT_ENDPOINT
    URLSCAN_TIMEOUT_SECONDS: int = URLSCAN_TIMEOUT_SECONDS
    URLSCAN_POLL_INTERVAL_SECONDS: int = URLSCAN_POLL_INTERVAL_SECONDS
    URLSCAN_MAX_POLL_TIME_SECONDS: int = URLSCAN_MAX_POLL_TIME_SECONDS
    URLSCAN_DAILY_RATE_LIMIT: int = URLSCAN_DAILY_RATE_LIMIT
    URLSCAN_MALICIOUS_LOG_THRESHOLD: int = URLSCAN_MALICIOUS_LOG_THRESHOLD
    URLSCAN_MAX_NETWORK_REQUESTS_TO_PARSE: int = URLSCAN_MAX_NETWORK_REQUESTS_TO_PARSE

    ABUSEIPDB_BASE_URL: str = ABUSEIPDB_BASE_URL
    ABUSEIPDB_TIMEOUT_SECONDS: int = ABUSEIPDB_TIMEOUT_SECONDS

    LOG_REQUEST_START: str = LOG_REQUEST_START
    LOG_REQUEST_SUCCESS: str = LOG_REQUEST_SUCCESS
    LOG_REQUEST_FAILURE: str = LOG_REQUEST_FAILURE
    LOG_RATE_LIMIT: str = LOG_RATE_LIMIT
    LOG_TIMEOUT: str = LOG_TIMEOUT

    BLACKLIST_HIT_WEIGHT: int = BLACKLIST_HIT_WEIGHT
    SUSPICIOUS_PROVIDER_WEIGHT: int = SUSPICIOUS_PROVIDER_WEIGHT
    HIGH_CONFIDENCE_THRESHOLD: int = HIGH_CONFIDENCE_THRESHOLD
    MEDIUM_CONFIDENCE_THRESHOLD: int = MEDIUM_CONFIDENCE_THRESHOLD
    LOW_CONFIDENCE_THRESHOLD: int = LOW_CONFIDENCE_THRESHOLD

    VIRUSTOTAL_MALICIOUS_THRESHOLD: int = VIRUSTOTAL_MALICIOUS_THRESHOLD
    ABUSEIPDB_MALICIOUS_THRESHOLD: int = ABUSEIPDB_MALICIOUS_THRESHOLD
    ABUSEIPDB_SUSPICIOUS_THRESHOLD: int = ABUSEIPDB_SUSPICIOUS_THRESHOLD
    ABUSEIPDB_REPORTS_THRESHOLD: int = ABUSEIPDB_REPORTS_THRESHOLD
    URLSCAN_LOCAL_MALICIOUS_THRESHOLD: float = URLSCAN_LOCAL_MALICIOUS_THRESHOLD
    URLSCAN_LOCAL_SUSPICIOUS_THRESHOLD: float = URLSCAN_LOCAL_SUSPICIOUS_THRESHOLD
    URLSCAN_FORM_MALICIOUS_THRESHOLD: float = URLSCAN_FORM_MALICIOUS_THRESHOLD
    URLSCAN_FORM_SUSPICIOUS_THRESHOLD: float = URLSCAN_FORM_SUSPICIOUS_THRESHOLD
    URLSCAN_HOSTING_SUSPICIOUS_THRESHOLD: float = URLSCAN_HOSTING_SUSPICIOUS_THRESHOLD
    URLSCAN_REDIRECT_THRESHOLD: int = URLSCAN_REDIRECT_THRESHOLD
    URLSCAN_GLOBAL_MALICIOUS_THRESHOLD: float = URLSCAN_GLOBAL_MALICIOUS_THRESHOLD
    URLSCAN_MALICIOUS_SCORE_THRESHOLD: int = URLSCAN_MALICIOUS_SCORE_THRESHOLD

    BLACKLIST_SCORE_WEIGHT: int = BLACKLIST_SCORE_WEIGHT
    BEHAVIORAL_SCORE_WEIGHT: int = BEHAVIORAL_SCORE_WEIGHT
    REPUTATION_SCORE_WEIGHT: int = REPUTATION_SCORE_WEIGHT

    HIGH_RISK_THRESHOLD: int = HIGH_RISK_THRESHOLD
    MEDIUM_RISK_THRESHOLD: int = MEDIUM_RISK_THRESHOLD
