from enum import Enum

class ValidationErrorCode(Enum):
    INVALID_URL_FORMAT = "INVALID_URL_FORMAT"
    INVALID_SCHEME = "INVALID_SCHEME"
    URL_TOO_LONG = "URL_TOO_LONG"
    SSRF_ATTEMPT = "SSRF_ATTEMPT"


class URLSignal(Enum):
    RAW_IP_ADDRESS = "RAW_IP_ADDRESS"
    PRIVATE_IP_TARGET = "PRIVATE_IP_TARGET"
    PUNYCODE_DOMAIN = "PUNYCODE_DOMAIN"
    UNICODE_DOMAIN = "UNICODE_DOMAIN"
    SUSPICIOUS_TLD = "SUSPICIOUS_TLD"